language: ruby
rvm:
  - "2.4.10"
  - "2.5"
  - "2.6"
  - "2.7"
env:
  global:
    - CC_TEST_REPORTER_ID=2177997ae2dd26804c32e1ec34a2221f94b71a2170f6c1db2c020f8858cd87f2

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  apt:
    packages:
    - mafft
