language: ruby
rvm:
  - "2.2.10"
before_script:
  - rake package:linux:x86_64 DIR_ONLY=1

  - echo $PATH
  - export PATH=$PWD/genevalidator-linux-x86_64/bin
script: bundle exec rake test
after_script: bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 2177997ae2dd26804c32e1ec34a2221f94b71a2170f6c1db2c020f8858cd87f2
