language: ruby
rvm:
  - "2.4.10"
  - "2.5"
  - "2.6"
  - "2.7"
script: bundle exec rake test
after_script: bundle exec codeclimate-test-reporter
addons:
  code_climate:
    repo_token: 2177997ae2dd26804c32e1ec34a2221f94b71a2170f6c1db2c020f8858cd87f2
  apt:
    packages:
    - mafft
